// Command Kota-cli is a CLI + REPL for the Kota SDK,
// built on the boru engine. Positional arguments are joined into a
// single boru expression and evaluated; with no arguments, falls into
// a REPL. Generated by sdkgen go-cli target.
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	"github.com/boru-lang/boru/eng/go/parser"
	sdk "github.com/voxgig-sdk/kota-sdk/go"
)

// prompt is the REPL prompt prefix (matches the SDK slug).
const prompt = "kota"

// entitiesHelp is the space-separated entity list shown by /help.
const entitiesHelp = "associated_person associated_person_eligibility_response_paged_list contribution_report contribution_report_employee_breakdown contribution_report_employee_breakdown_response_paged_list create_hosted_session_token create_session_token dependent dependents_management_intent eligibility_check employee employee_health_insurance_offer employee_health_insurance_offer_response_paged_list employee_health_insurance_policy employee_health_insurance_policy_response_paged_list employer employer_health_insurance_policy employer_health_insurance_policy_response_paged_list employer_health_insurance_quote employer_health_insurance_quote_response_paged_list enrolment_intent enrolment_intent_requirement_response_paged_list event group group_employee group_employee_response_paged_list group_policy group_policy_intent group_policy_intent_requirement_response_paged_list group_quote group_quote_intent group_quote_intent_requirement_response_paged_list plan policy policy_amendment_intent policy_import_intent provider replay webhook_endpoint webhook_endpoint_response_paged_list"

func main() {
	os.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}

// usage prints the CLI help (for --help / -h). No client or network setup.
func usage(out io.Writer) {
	fmt.Fprintf(out, "%s-cli — boru-driven CLI + REPL for the %s SDK\n\n", prompt, prompt)
	fmt.Fprintln(out, "Usage:")
	fmt.Fprintf(out, "  %s-cli [--help] [<boru expression>]\n\n", prompt)
	fmt.Fprintln(out, "With arguments, they are joined into a single boru expression and")
	fmt.Fprintln(out, "evaluated against the API. With no arguments, starts an interactive REPL.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Words:    list / load / update <query?> <entity>")
	fmt.Fprintln(out, "Entities:", entitiesHelp)
	fmt.Fprintln(out, "Env:      KOTA_APIKEY (api key), KOTA_BASE (base url override)")
	fmt.Fprintln(out, "REPL:     /help  /quit")
}

func run(args []string, in io.Reader, out, errOut io.Writer) int {
	// --help / -h: print usage and exit before any config or network setup.
	for _, a := range args {
		if a == "--help" || a == "-h" {
			usage(out)
			return 0
		}
	}

	// Configure from the environment: KOTA_APIKEY carries the API key and
	// KOTA_BASE optionally overrides the API base URL (e.g. production).
	// Both injectable by a secrets vault. Unset -> nil config defaults.
	var opts map[string]any
	if apikey := os.Getenv("KOTA_APIKEY"); apikey != "" {
		opts = map[string]any{"apikey": apikey}
	}
	if base := os.Getenv("KOTA_BASE"); base != "" {
		if opts == nil {
			opts = map[string]any{}
		}
		opts["base"] = base
	}
	client := sdk.NewKotaSDK(opts)

	r, err := eng.NewRegistry()
	if err != nil {
		fmt.Fprintf(errOut, "registry: %v\n", err)
		return 1
	}
	registerSDKWords(r, client)
	if err := r.Err(); err != nil {
		fmt.Fprintf(errOut, "word registration: %v\n", err)
		return 1
	}
	r.SetParseFunc(parser.Parse)
	r.InitRootContext()
	r.MarkReady()

	if len(args) > 0 {
		return evalOnce(r, strings.Join(args, " "), out, errOut)
	}
	repl(r, in, out)
	return 0
}

func evalOnce(r *eng.Registry, src string, out, errOut io.Writer) int {
	values, err := parser.Parse(src)
	if err != nil {
		fmt.Fprintf(errOut, "parse: %v\n", err)
		return 1
	}
	result, err := eng.NewTop(r).Run(values)
	if err != nil {
		fmt.Fprintf(errOut, "error: %v\n", err)
		return 1
	}
	for _, v := range result {
		fmt.Fprintln(out, v.String())
	}
	return 0
}

func repl(r *eng.Registry, in io.Reader, out io.Writer) {
	scanner := bufio.NewScanner(in)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for {
		fmt.Fprintf(out, "%s> ", prompt)
		if !scanner.Scan() {
			fmt.Fprintln(out)
			return
		}
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		switch line {
		case "/quit", "/q", "/exit":
			return
		case "/help", "/h", "/?":
			fmt.Fprintln(out, "words:    list / load / update <query?> <entity>")
			fmt.Fprintln(out, "entities:", entitiesHelp)
			fmt.Fprintln(out, "meta:     /help  /quit")
			continue
		}
		values, err := parser.Parse(line)
		if err != nil {
			fmt.Fprintf(out, "  parse error: %v\n", err)
			continue
		}
		result, err := eng.NewTop(r).Run(values)
		if err != nil {
			fmt.Fprintf(out, "  error: %v\n", err)
			continue
		}
		for _, v := range result {
			fmt.Fprintln(out, v.String())
		}
	}
}
