// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/kota-sdk/go"
)

// registerSDKWords installs three native boru words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word. Both
// overloads are all-forward (BarrierAllForward), so args are collected
// from the tokens following the word.
func registerSDKWords(r *eng.Registry, client *sdk.KotaSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.KotaSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.KotaSDK, name string) (sdk.KotaEntity, error) {
	switch strings.ToLower(name) {
	case "associated_person":
		return client.AssociatedPerson(nil), nil
	case "associated_person_eligibility_response_paged_list":
		return client.AssociatedPersonEligibilityResponsePagedList(nil), nil
	case "contribution_report":
		return client.ContributionReport(nil), nil
	case "contribution_report_employee_breakdown":
		return client.ContributionReportEmployeeBreakdown(nil), nil
	case "contribution_report_employee_breakdown_response_paged_list":
		return client.ContributionReportEmployeeBreakdownResponsePagedList(nil), nil
	case "create_hosted_session_token":
		return client.CreateHostedSessionToken(nil), nil
	case "create_session_token":
		return client.CreateSessionToken(nil), nil
	case "dependent":
		return client.Dependent(nil), nil
	case "dependents_management_intent":
		return client.DependentsManagementIntent(nil), nil
	case "eligibility_check":
		return client.EligibilityCheck(nil), nil
	case "employee":
		return client.Employee(nil), nil
	case "employee_health_insurance_offer":
		return client.EmployeeHealthInsuranceOffer(nil), nil
	case "employee_health_insurance_offer_response_paged_list":
		return client.EmployeeHealthInsuranceOfferResponsePagedList(nil), nil
	case "employee_health_insurance_policy":
		return client.EmployeeHealthInsurancePolicy(nil), nil
	case "employee_health_insurance_policy_response_paged_list":
		return client.EmployeeHealthInsurancePolicyResponsePagedList(nil), nil
	case "employer":
		return client.Employer(nil), nil
	case "employer_health_insurance_policy":
		return client.EmployerHealthInsurancePolicy(nil), nil
	case "employer_health_insurance_policy_response_paged_list":
		return client.EmployerHealthInsurancePolicyResponsePagedList(nil), nil
	case "employer_health_insurance_quote":
		return client.EmployerHealthInsuranceQuote(nil), nil
	case "employer_health_insurance_quote_response_paged_list":
		return client.EmployerHealthInsuranceQuoteResponsePagedList(nil), nil
	case "enrolment_intent":
		return client.EnrolmentIntent(nil), nil
	case "enrolment_intent_requirement_response_paged_list":
		return client.EnrolmentIntentRequirementResponsePagedList(nil), nil
	case "event":
		return client.Event(nil), nil
	case "group":
		return client.Group(nil), nil
	case "group_employee":
		return client.GroupEmployee(nil), nil
	case "group_employee_response_paged_list":
		return client.GroupEmployeeResponsePagedList(nil), nil
	case "group_policy":
		return client.GroupPolicy(nil), nil
	case "group_policy_intent":
		return client.GroupPolicyIntent(nil), nil
	case "group_policy_intent_requirement_response_paged_list":
		return client.GroupPolicyIntentRequirementResponsePagedList(nil), nil
	case "group_quote":
		return client.GroupQuote(nil), nil
	case "group_quote_intent":
		return client.GroupQuoteIntent(nil), nil
	case "group_quote_intent_requirement_response_paged_list":
		return client.GroupQuoteIntentRequirementResponsePagedList(nil), nil
	case "plan":
		return client.Plan(nil), nil
	case "policy":
		return client.Policy(nil), nil
	case "policy_amendment_intent":
		return client.PolicyAmendmentIntent(nil), nil
	case "policy_import_intent":
		return client.PolicyImportIntent(nil), nil
	case "provider":
		return client.Provider(nil), nil
	case "replay":
		return client.Replay(nil), nil
	case "webhook_endpoint":
		return client.WebhookEndpoint(nil), nil
	case "webhook_endpoint_response_paged_list":
		return client.WebhookEndpointResponsePagedList(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
