// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/kota-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"associated_person | associated_person_eligibility_response_paged_list | contribution_report | contribution_report_employee_breakdown | contribution_report_employee_breakdown_response_paged_list | create_hosted_session_token | create_session_token | dependent | dependents_management_intent | eligibility_check | employee | employee_health_insurance_offer | employee_health_insurance_offer_response_paged_list | employee_health_insurance_policy | employee_health_insurance_policy_response_paged_list | employer | employer_health_insurance_policy | employer_health_insurance_policy_response_paged_list | employer_health_insurance_quote | employer_health_insurance_quote_response_paged_list | enrolment_intent | enrolment_intent_requirement_response_paged_list | event | group | group_employee | group_employee_response_paged_list | group_policy | group_policy_intent | group_policy_intent_requirement_response_paged_list | group_quote | group_quote_intent | group_quote_intent_requirement_response_paged_list | plan | policy | policy_amendment_intent | policy_import_intent | provider | replay | webhook_endpoint | webhook_endpoint_response_paged_list"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.KotaSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "kota_list",
		Description: "List records from Kota. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "kota_load",
		Description: "Load a single record from Kota. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.KotaSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.KotaSDK, name string) (sdk.KotaEntity, error) {
	switch strings.ToLower(name) {
	case "associated_person":
		return client.AssociatedPerson(nil), nil
	case "associated_person_eligibility_response_paged_list":
		return client.AssociatedPersonEligibilityResponsePagedList(nil), nil
	case "contribution_report":
		return client.ContributionReport(nil), nil
	case "contribution_report_employee_breakdown":
		return client.ContributionReportEmployeeBreakdown(nil), nil
	case "contribution_report_employee_breakdown_response_paged_list":
		return client.ContributionReportEmployeeBreakdownResponsePagedList(nil), nil
	case "create_hosted_session_token":
		return client.CreateHostedSessionToken(nil), nil
	case "create_session_token":
		return client.CreateSessionToken(nil), nil
	case "dependent":
		return client.Dependent(nil), nil
	case "dependents_management_intent":
		return client.DependentsManagementIntent(nil), nil
	case "eligibility_check":
		return client.EligibilityCheck(nil), nil
	case "employee":
		return client.Employee(nil), nil
	case "employee_health_insurance_offer":
		return client.EmployeeHealthInsuranceOffer(nil), nil
	case "employee_health_insurance_offer_response_paged_list":
		return client.EmployeeHealthInsuranceOfferResponsePagedList(nil), nil
	case "employee_health_insurance_policy":
		return client.EmployeeHealthInsurancePolicy(nil), nil
	case "employee_health_insurance_policy_response_paged_list":
		return client.EmployeeHealthInsurancePolicyResponsePagedList(nil), nil
	case "employer":
		return client.Employer(nil), nil
	case "employer_health_insurance_policy":
		return client.EmployerHealthInsurancePolicy(nil), nil
	case "employer_health_insurance_policy_response_paged_list":
		return client.EmployerHealthInsurancePolicyResponsePagedList(nil), nil
	case "employer_health_insurance_quote":
		return client.EmployerHealthInsuranceQuote(nil), nil
	case "employer_health_insurance_quote_response_paged_list":
		return client.EmployerHealthInsuranceQuoteResponsePagedList(nil), nil
	case "enrolment_intent":
		return client.EnrolmentIntent(nil), nil
	case "enrolment_intent_requirement_response_paged_list":
		return client.EnrolmentIntentRequirementResponsePagedList(nil), nil
	case "event":
		return client.Event(nil), nil
	case "group":
		return client.Group(nil), nil
	case "group_employee":
		return client.GroupEmployee(nil), nil
	case "group_employee_response_paged_list":
		return client.GroupEmployeeResponsePagedList(nil), nil
	case "group_policy":
		return client.GroupPolicy(nil), nil
	case "group_policy_intent":
		return client.GroupPolicyIntent(nil), nil
	case "group_policy_intent_requirement_response_paged_list":
		return client.GroupPolicyIntentRequirementResponsePagedList(nil), nil
	case "group_quote":
		return client.GroupQuote(nil), nil
	case "group_quote_intent":
		return client.GroupQuoteIntent(nil), nil
	case "group_quote_intent_requirement_response_paged_list":
		return client.GroupQuoteIntentRequirementResponsePagedList(nil), nil
	case "plan":
		return client.Plan(nil), nil
	case "policy":
		return client.Policy(nil), nil
	case "policy_amendment_intent":
		return client.PolicyAmendmentIntent(nil), nil
	case "policy_import_intent":
		return client.PolicyImportIntent(nil), nil
	case "provider":
		return client.Provider(nil), nil
	case "replay":
		return client.Replay(nil), nil
	case "webhook_endpoint":
		return client.WebhookEndpoint(nil), nil
	case "webhook_endpoint_response_paged_list":
		return client.WebhookEndpointResponsePagedList(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
