<?php
declare(strict_types=1);

// Kota SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

KotaUtility::setRegistrar(function (KotaUtility $u): void {
    $u->clean = [KotaClean::class, 'call'];
    $u->done = [KotaDone::class, 'call'];
    $u->make_error = [KotaMakeError::class, 'call'];
    $u->feature_add = [KotaFeatureAdd::class, 'call'];
    $u->feature_hook = [KotaFeatureHook::class, 'call'];
    $u->feature_init = [KotaFeatureInit::class, 'call'];
    $u->fetcher = [KotaFetcher::class, 'call'];
    $u->make_fetch_def = [KotaMakeFetchDef::class, 'call'];
    $u->make_context = [KotaMakeContext::class, 'call'];
    $u->make_options = [KotaMakeOptions::class, 'call'];
    $u->make_request = [KotaMakeRequest::class, 'call'];
    $u->make_response = [KotaMakeResponse::class, 'call'];
    $u->make_result = [KotaMakeResult::class, 'call'];
    $u->make_point = [KotaMakePoint::class, 'call'];
    $u->make_spec = [KotaMakeSpec::class, 'call'];
    $u->make_url = [KotaMakeUrl::class, 'call'];
    $u->param = [KotaParam::class, 'call'];
    $u->prepare_auth = [KotaPrepareAuth::class, 'call'];
    $u->prepare_body = [KotaPrepareBody::class, 'call'];
    $u->prepare_headers = [KotaPrepareHeaders::class, 'call'];
    $u->prepare_method = [KotaPrepareMethod::class, 'call'];
    $u->prepare_params = [KotaPrepareParams::class, 'call'];
    $u->prepare_path = [KotaPreparePath::class, 'call'];
    $u->prepare_query = [KotaPrepareQuery::class, 'call'];
    $u->graphql_body = [KotaGraphql::class, 'body'];
    $u->graphql_errors = [KotaGraphql::class, 'errors'];
    $u->result_basic = [KotaResultBasic::class, 'call'];
    $u->result_body = [KotaResultBody::class, 'call'];
    $u->result_headers = [KotaResultHeaders::class, 'call'];
    $u->transform_request = [KotaTransformRequest::class, 'call'];
    $u->transform_response = [KotaTransformResponse::class, 'call'];
});
